name: Java Build & Release

on:
  push:
    branches:
      - main
      - CLIENT-3877-fix-javadoc-jar
  workflow_dispatch:
  #   - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-stage:
    name: Build stage
    uses: ./.github/workflows/build-release.yml
    secrets: inherit