name: Java Build & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:
  #   - '[0-9]+.[0-9]+.[0-9]+'

jobs:
  build-stage:
    name: Build stage
    uses: ./.github/workflows/build-release.yaml
    secrets: inherit